# 영업 성공 여부 분류 경진대회

# 할 것

결측치 이상치 처리
파생변수 생성

## 1. 데이터 확인

### 필수 라이브러리

In [ ]:
# !pip uninstall googletrans -y
# !pip install googletrans==3.1.0a0

In [1]:
import re
import pandas as pd
import numpy as np
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
)

from sklearn.model_selection import StratifiedKFold
from sklearn.utils.class_weight import compute_class_weight
from catboost import CatBoostClassifier
from sklearn.metrics import f1_score

from googletrans import Translator
translator = Translator()

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

def seed_everything(seed):
    np.random.seed(seed) #numpy를 사용할 경우 고정
seed_everything(42)

### 데이터 셋 읽어오기

In [2]:
df_train = pd.read_csv("train.csv") # 학습용 데이터
df_test = pd.read_csv("submission.csv") # 테스트 데이터(제출파일의 데이터)

In [3]:
df_train[:10]

,bant_submit,customer_country,business_unit,com_reg_ver_win_rate,customer_idx,customer_type,enterprise,historical_existing_cnt,id_strategic_ver,it_strategic_ver,idit_strategic_ver,customer_job,lead_desc_length,inquiry_type,product_category,product_subcategory,product_modelname,customer_country.1,customer_position,response_corporate,expected_timeline,ver_cus,ver_pro,ver_win_rate_x,ver_win_ratio_per_bu,business_area,business_subarea,lead_owner,is_converted
0,1.00,/Quezon City/Philippines,AS,0.066667,32160,End-Customer,Enterprise,NaN,NaN,NaN,NaN,purchasing,62,Quotation or purchase consultation,multi-split,NaN,NaN,/Quezon City/Philippines,entry level,LGEPH,less than 3 months,1,0,0.003079,0.026846,corporate / office,Engineering,0,True
1,1.00,/PH-00/Philippines,AS,0.066667,23122,End-Customer,Enterprise,12.0,NaN,NaN,NaN,media and communication,96,Quotation or purchase consultation,multi-split,NaN,NaN,/PH-00/Philippines,ceo/founder,LGEPH,less than 3 months,1,0,0.003079,0.026846,corporate / office,Advertising,1,True
2,1.00,/Kolkata /India,AS,0.088889,1755,End-Customer,Enterprise,144.0,NaN,NaN,NaN,engineering,56,Product Information,single-split,NaN,NaN,/Kolkata /India,partner,LGEIL,less than 3 months,1,0,0.003079,0.026846,corporate / office,Construction,2,True
3,1.00,/Bhubaneswar/India,AS,0.088889,4919,End-Customer,Enterprise,NaN,NaN,NaN,NaN,entrepreneurship,44,Quotation or purchase consultation,vrf,NaN,NaN,/Bhubaneswar/India,ceo/founder,LGEIL,less than 3 months,1,0,0.003079,0.026846,corporate / office,IT/Software,3,True
4,1.00,/Hyderabad/India,AS,0.088889,17126,Specifier/ Influencer,Enterprise,NaN,NaN,NaN,NaN,consulting,97,Quotation or purchase consultation,multi-split,NaN,NaN,/Hyderabad/India,partner,LGEIL,less than 3 months,0,0,0.003079,0.026846,corporate / office,NaN,4,True
5,1.00,/Abuja/Nigeria,AS,0.040816,16328,End-Customer,SMB,NaN,NaN,NaN,NaN,program and project management,1114,Quotation or purchase consultation,chiller,NaN,NaN,/Abuja/Nigeria,manager,LGEAF,less than 3 months,1,0,0.003079,0.026846,corporate / office,Engineering,5,True
6,0.75,"/Jeddah, KSA/Saudi Arabia",AS,0.040816,20664,End-Customer,SMB,NaN,NaN,NaN,NaN,engineering,420,Quotation or purchase consultation,single-split,NaN,NaN,"/Jeddah, KSA/Saudi Arabia",manager,LGESJ,NaN,1,0,0.003079,0.026846,corporate / office,Engineering,6,True
7,1.00,/Guwahati/India,AS,0.088889,17983,End-Customer,SMB,NaN,NaN,NaN,NaN,sales,205,Quotation or purchase consultation,vrf,NaN,NaN,/Guwahati/India,partner,LGEIL,less than 3 months,1,0,0.003079,0.026846,corporate / office,Manufacturing,7,True
8,0.75,/Cebu city/Philippines,AS,0.066667,30867,Specifier/ Influencer,Enterprise,3.0,NaN,NaN,NaN,other,103,Quotation or purchase consultation,multi-split,NaN,NaN,/Cebu city/Philippines,vice president,LGEPH,less than 3 months,0,0,0.003079,0.026846,corporate / office,Construction,8,True
9,0.75,"/hauz khas,delhi/India",AS,0.088889,6084,End-Customer,SMB,NaN,NaN,NaN,NaN,other,252,Quotation or purchase consultation,vrf,NaN,NaN,"/hauz khas,delhi/India",manager,LGEIL,3 months ~ 6 months,1,0,0.003079,0.026846,corporate / office,NaN,9,True

In [4]:
# 결측치가 있는 변수 및 결측률 파악 

mis_val = df_train.isnull().sum()
mis_val_bool = mis_val >= 1
mis_val_df = pd.concat([mis_val, mis_val_bool], axis = 1)
mis_val_df = mis_val_df.rename(columns = {0 : 'mis_val', 1 : 'mis_val_bool'})

mis_val_data = mis_val_df.loc[mis_val_df['mis_val_bool'] == True, :]
mis_val_data['ratio'] = mis_val_data['mis_val'] / 59299
mis_val_data_sorted = mis_val_data.sort_values(by='ratio', ascending=True)
mis_val_data_sorted

/tmp/ipykernel_76/929980573.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mis_val_data['ratio'] = mis_val_data['mis_val'] / 59299

                         mis_val  mis_val_bool     ratio
inquiry_type                 941          True  0.015869
customer_country.1           982          True  0.016560
customer_country             982          True  0.016560
customer_job               18733          True  0.315908
product_category           19374          True  0.326717
expected_timeline          30863          True  0.520464
business_area              40882          True  0.689421
ver_win_rate_x             40882          True  0.689421
customer_type              43961          True  0.741345
ver_win_ratio_per_bu       43995          True  0.741918
com_reg_ver_win_rate       44731          True  0.754330
historical_existing_cnt    45543          True  0.768023
product_subcategory        50064          True  0.844264
product_modelname          50070          True  0.844365
business_subarea           53773          True  0.906811
idit_strategic_ver         54734          True  0.923017
id_strategic_ver           55855          True  0.941921
it_strategic_ver           58178          True  0.981096

In [5]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59299 entries, 0 to 59298
Data columns (total 29 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   bant_submit              59299 non-null  float64
 1   customer_country         58317 non-null  object
 2   business_unit            59299 non-null  object
 3   com_reg_ver_win_rate     14568 non-null  float64
 4   customer_idx             59299 non-null  int64
 5   customer_type            15338 non-null  object
 6   enterprise               59299 non-null  object
 7   historical_existing_cnt  13756 non-null  float64
 8   id_strategic_ver         3444 non-null   float64
 9   it_strategic_ver         1121 non-null   float64
 10  idit_strategic_ver       4565 non-null   float64
 11  customer_job             40566 non-null  object
 12  lead_desc_length         59299 non-null  int64
 13  inquiry_type             58358 non-null  object
 14  product_category         39925 non-null  object
 15  product_subcategory      9235 non-null   object
 16  product_modelname        9229 non-null   object
 17  customer_country.1       58317 non-null  object
 18  customer_position        59299 non-null  object
 19  response_corporate       59299 non-null  object
 20  expected_timeline        28436 non-null  object
 21  ver_cus                  59299 non-null  int64
 22  ver_pro                  59299 non-null  int64
 23  ver_win_rate_x           18417 non-null  float64
 24  ver_win_ratio_per_bu     15304 non-null  float64
 25  business_area            18417 non-null  object
 26  business_subarea         5526 non-null   object
 27  lead_owner               59299 non-null  int64
 28  is_converted             59299 non-null  bool
dtypes: bool(1), float64(8), int64(5), object(15)
memory usage: 12.7+ MB

### 전처리
customer_country.1 열 삭제

float -> 범주형 데이터로 변환 ['it_strategic_ver','id_strategic_ver','idit_strategic_ver','lead_owner','ver_cus','ver_pro','customer_idx']

inquiry_type,customer_country - 대소문자 통합

customer_country 결측치 행 삭제

이상치 - MinMaxScale

## 추가된 전처리

### 언어 통일

customer_country : 방식 수정. 처리 안되는 부분이 있었음.

customer_job : 유사한 직업으로 묶음.

product_category : 여러 category를 가진 경우, 여러 행으로 분해

In [6]:
# customer_country , customer_country.1의 값이 일치함.
pre_train = df_train.drop(labels = ['customer_country.1'],axis=1)
pre_test = df_test.drop(labels = ['customer_country.1','id'],axis=1)

dtypes = pre_train.dtypes

# 각 열의 고유값 개수 확인
unique_value_counts = pre_train.nunique()

# 수치형 변수가 아닌 컬럼을 저장할 리스트 초기화
object_columns = []

# 각 열에 대해 데이터 타입이 'object'이거나 고유값 개수가 일정 이하인 경우를 확인하여 non_numeric_columns 리스트에 추가
for col in pre_train.columns:
    if dtypes[col] == 'object':
        object_columns.append(col)

# 수치형 변수가 아닌 컬럼 출력
print("범주형 컬럼:", object_columns,"\n")
print("수치형 컬럼 :", list(set(pre_train.columns)-set(object_columns)))

범주형 컬럼: ['customer_country', 'business_unit', 'customer_type', 'enterprise', 'customer_job', 'inquiry_type', 'product_category', 'product_subcategory', 'product_modelname', 'customer_position', 'response_corporate', 'expected_timeline', 'business_area', 'business_subarea']

수치형 컬럼 : ['customer_idx', 'ver_win_rate_x', 'idit_strategic_ver', 'ver_win_ratio_per_bu', 'it_strategic_ver', 'bant_submit', 'id_strategic_ver', 'ver_pro', 'ver_cus', 'historical_existing_cnt', 'com_reg_ver_win_rate', 'lead_desc_length', 'is_converted', 'lead_owner']

In [7]:
# 범주형으로 변경
columns_categorized = ['it_strategic_ver','id_strategic_ver','idit_strategic_ver'] + ['lead_owner','ver_cus','ver_pro','customer_idx']

for n in columns_categorized:
    pre_train[n] = pre_train[n].fillna(0)
    pre_train[n] = pre_train[n].astype('int').astype('object')

In [8]:
print(pre_train['product_category'].unique())

['multi-split' 'single-split' 'vrf' 'chiller' 'etc.' 'rac'
 'teto ou cassete inverter' nan 'software solution' 'all lg vrf systems'
 'ventilation' 'a thermodynamic water heater'
 'residential air conditioner' 'outros' 'heating' 'multi v5 vrf'
 'split tunggal' 'multi inverter' 'חימום' 'standard signage'
 'high brightness signage' 'interactive signage' 'video wall signage'
 'led signage' 'hotel tv' 'signage care solution' 'oled signage' 'idb'
 'video wall' 'one:quick series' 'commercial tv' 'lg one:quick'
 'special signage' 'other' 'accessories' 'commercial display'
 'interactive digital board' 'standard' 'uhd signage' 'smart tv signage'
 'lg one:quick series' 'pro:centric' 'ur640' 'ur640s' 'webos'
 'signage care solutions' 'aio | one quick' 'high brightness'
 'hospital tv' 'digital signage' 'monitor' 'pc' 'laptop' 'projector'
 'cloud device' 'medical display' 'washing machine,dryer' 'solar,chiller'
 'system ac,rac' 'monitor signage,commercial tv,monior/monitor tv'
 'monitor signage,monior/monitor tv' 'aircare,built-in/cooking'
 'monitor signage,commercial tv,monior/monitor tv,projector,tv'
 'monitor signage,commercial tv,monior/monitor tv,tv' 'commercial tv,tv'
 'monitor signage,commercial tv,solar,ess,monior/monitor tv,pc,projector,robot,system ac,ems,rac,chill'
 'monior/monitor tv,tv' 'chiller,aircare' 'solar,aircare'
 'commercial tv,audio/video' 'solar,ess' 'solar,system ac'
 'ultra stretch series' '互動式顯示屏' 'led 顯示屏' 'one quick works' 'fhd series'
 'onequick series' '標準顯示屏' '43us660h0sd.awz' '50uq801c0sb.bwz'
 'one quick:flex' 'led aio 136' '110 + video wall' 'aio' 'tv'
 'videowall signage' '酒店電視' 'robots' 'one:quick flex' 'tv signage'
 'collaboration displays' 'oled 顯示屏' 'id'
 'meeting & screen sharedirect view leddirect view led'
 'window facing display' 'lg customer care program' 'led' 'lainnya'
 'multi v' 'control' 'מזגנים למקום מגורים' 'pendingin' 'multi v 5 air'
 'ar condicionado residencial' 'مبرد (تشيلر)' 'multi v water 5'
 'single split' 'ahu' 'multi split' 'lg home bliss air solution'
 'lg paradise air solution' 'isıtma' 'technical support' 'تكييفات'
 'sales inquiry' 'פיצול מרובה' 'تكييف وتبريد' 'אחר' 'vrf,multi-split'
 'vrf,multi-split,chiller' 'vrf,multi-split,single-split,chiller,heating'
 'error' 'medical displays' 'others' '28mq780' 'computer monitors'
 'monitor & pc' 'medical monitors' 'system air conditioner'
 'system ac,solar,washing machine' 'solar,ess,ems' 'tv,mobile'
 'commercial tv,projector' 'aircare,water care'
 'monior/monitor tv,chiller' 'system ac,chiller' 'system ac,aircare'
 'monitor signage,commercial tv' 'system ac,tv'
 'monitor signage,audio/video'
 'monitor signage,commercial tv,solar,ess,monior/monitor tv,pc'
 'monitor signage,pc' 'monitor signage,commercial tv,solar,ess' 'solar'
 'energy storage system'
 'monior/monitor tv,system ac,tv,refrigerator,washing machine,dryer,built-in/cooking'
 'commercial tv,robot' 'monitor signage,solar' 'solar,projector'
 'tv,audio/video' 'refrigerator' 'solar,dryer' 'solar,monior/monitor tv'
 'chiller,dryer' 'monior/monitor tv,pc' 'solar,refrigerator'
 'monitor signage,system ac' 'system air conditioner,solar' 'solar,tv'
 'monitor signage,tv' 'dryer,chiller'
 'monitor signage,monior/monitor tv,system ac,vacuum cleaner,tv,home beauty,commercial tv,mobile,audio'
 'videwall' 'ultra stretch signage' 'solar,vacuum cleaner'
 'solar,monior/monitor tv,pc,tv,refrigerator,washing machine,dryer,home beauty'
 'monitor signage,solar,robot,water care' 'mobile,audio/video'
 'system ac,refrigerator,washing machine,dryer' 'solar,system ac,aircare'
 'projector,system ac,water care' 'chiller,water care'
 'monior/monitor tv,tv,commercial tv,pc,refrigerator,solar,rac,washing machine,mobile,ess,audio/video'
 'ess,chiller' 'monitor signage,monior/monitor tv,pc,tv'
 'solar,water care' 'digital signage or commercial tvs'
 'education createboard' 'virtual production' 'laec015'
 'monitor signage,commercial tv,audio/video' 'solar,built-in/cooking'
 'monitor signage,monior/monitor tv,commercial tv'
 'commercial tv,monior/monitor tv' 'robot,system ac' '55us660h0sd.bwz'
 'transparent oled' 'medical- surgical' 'radiology displays'
 'high inch 86 / 98 or 110' 'leadallin' 'ฯลฯ' 'commercial tv,water care'
 'pc,washing machine'
 'monitor signage,solar,monior/monitor tv,pc,projector,robot,system ac,tv,refrigerator,washing machine'
 'system ac,tv,refrigerator,washing machine,built-in/cooking,audio/video'
 'system air conditioner,energy storage system' 'tv,commercial tv'
 'system ac,home beauty' 'information display,monitor'
 'taa lcd lfd displays' 'rac/cac' 'حلول التدفئة'
 'system ac,chiller,aircare' 'otros' 'tv,refrigerator,washing machine'
 'monior/monitor tv,refrigerator'
 'monior/monitor tv,system ac,tv,pc,refrigerator,water care,solar,washing machine,mobile,chiller,built'
 'projector,audio/video' 'monior/monitor tv,audio/video'
 'monitor signage,commercial tv,monior/monitor tv,pc,tv,home beauty,audio/video'
 'pc,robot,system ac,chiller,tv,refrigerator,washing machine,vacuum cleaner,styler,dryer,mobile,audio/'
 'refrigerator,washing machine,built-in/cooking'
 'monitor signage,monior/monitor tv,tv,audio/video'
 'tv,refrigerator,washing machine,vacuum cleaner,audio/video' 'pc,tv'
 'system ac' 'sac' 'laec015-gn.awz' 'gscd046' '32lq621cbsb.awz'
 '43uh5f-h.awzm' '49vl5g-m.awzm' '55uq801c0sb.bwz' '43uq751c0sf.bwz'
 '32 / 43 pol' 'htv' '43uq751c0sb.bwz' '49uh / 49xf' '50us660h0sd.bwz'
 'tv 60"' 'medical monitor' 'aircare,mobile' 'solar,ess,system ac'
 'system ac,refrigerator' 'tv,pc'
 'monitor signage,commercial tv,solar,pc,projector,system ac,ems,rac,chiller,refrigerator,washing mach'
 'chiller,refrigerator'
 'monitor signage,commercial tv,solar,projector,robot,chiller,refrigerator,built-in/cooking,water care'
 'commercial tv,solar' 'monior/monitor tv,projector,audio/video'
 'unitario' 'refrigerator,chiller' 'chiller,tv' 'projector,ems' 'cac'
 'vrf,chiller' 'single package' 'monitor signage,mobile'
 'robot,vacuum cleaner'
 'monitor signage,commercial tv,monior/monitor tv,audio/video'
 'điều hòa trung tâm multi' 'ogrzewanie (pompy ciepła)' 'soğutucu'
 'điều hòa gia dụng' 'نظام التدفق المتغيرvrf' 'chiller/enfriadoras'
 '49vl5g-m' 'lg led bloc' 'uh' '55vm5e-a' 'laec15' '55vm5j-h' '49vl5f'
 'standalone' 'corpouh5f' 'ledallinone' 'monitorindustrial_rmk'
 'lg magnit' '特別顯示屏' 'signage' 'videowall_rmk' 'bu50nst' 'led 70m2'
 'led cinema' '86uh5f' '55tc3d' '43us660h (na)' 'pro centric hotel'
 'video wall + aio' 'hospitality' 'one:quick' '高亮度顯示屏' 'comercial tv'
 'corpuh5f-' 'allinone_rmk' 'hoteleria_us670h' 'retaildigital' '軟體' '醫院電視'
 'ctv' 'calefacción' 'autre' 'vb.' 'ac rumah'
 'เครื่องปรับอากาศเผื่อที่อยู่อาศัย' 'aire acondicionado residencial'
 'vrf - multi v s' 'systèmes de débit à réfrigérant variable (drv)'
 'climatiseur résidentiel' 'multi-split (plusieurs pièces)' 'aquecimento'
 'khác' 'lg salang air solution for dream homes' 'rac single cac'
 'services' 'آخر' 'vrf,single-split'
 'vrf,multi-split,single-split,chiller,etc.' 'multi-split,single-split'
 'vrf,multi-split,single-split' 'vrf,multi-split,etc.'
 'vrf,multi-split,heating' 'on or several reversible ac'
 'vrf,multi-split,single-split,chiller'
 'vrf,multi-split,single-split,heating' 'vrf,single-split,chiller'
 'commercial tv,solar,ess,projector,system ac,tv,washing machine,home beauty,audio/video'
 'solar,robot' 'scroll compressor' 'pantalla led outdoor'
 'klimatyzacja multi-split'
 'monitor signage,commercial tv,monior/monitor tv,pc,projector,tv,audio/video'
 'not specified' 'single cac' 'kimatyzacja vrf'
 'solar,energy storage system' 'system ac,solar'
 'solar,system ac,water care' '55svh7f-a' 'tr3' '98uh5e' 'inne'
 'điều hòa trung tâm vrf' 'vrf,heating'
 'monitor signage,monior/monitor tv,vacuum cleaner,tv,home beauty,commercial tv,pc,refrigerator,styler'
 'refrigerator,built-in/cooking' 'ems,audio/video'
 'projector,ems,mobile,audio/video' 'smart tv' 'tv 55"' 'surgical monitor'
 'gsca046' 'gscd100' 'procentric' '32 pol' 'tv 43 pol' '43 pol'
 'commercial tv,solar,ess,monior/monitor tv,pc,projector,robot,system ac,ems,rac,chiller,refrigerator,'
 'tv,refrigerator' 'a definir' 'điều hòa trung tâm chiller'
 'điều hòa cục bộ' 'lsca039' 'essential series' 'parts'
 'monior/monitor tv,refrigerator,audio/video']

## 언어 통일 (00 -> 영어)

customer_job , inquiry_type , product_category , product_subcategory , product_modelname

시험 코드

In [9]:
translator = Translator()

def remove_special_characters(text):
    return re.sub(r'\W+', ' ', text)

def is_english(sentence):
    if sentence is np.nan:
        return sentence
    
    non_alpha_chars = re.sub(r'\W+', '', sentence)
    print(non_alpha_chars)
    non_alpha_chars = re.search(r'[^a-zA-Z]', non_alpha_chars)
    print(non_alpha_chars)
    
    if non_alpha_chars:
        changed_chars = translator.translate(sentence,dest='en').text 
#         return True
    else:
        changed_chars = sentence
    
    return changed_chars

# 특수 기호가 포함된 문자열 예시
n = np.nan
text_with_special_characters_1 = 'systèmes de débit à réfrigérant variable (drv)'
text_with_special_characters_2 = '醫院電視'
text_with_special_characters_3 = 'refrigerator,built-in/cooking'

# 특수 기호를 제거한 문자열 출력
print(is_english(text_with_special_characters_1))

systèmesdedébitàréfrigérantvariabledrv
<re.Match object; span=(4, 5), match='è'>
variable refrigerant flow (drv) systems

## 전처리 함수

In [10]:
def en_dic(df,col):
    unique_value = df[col].unique()
    trans_dic = {}
    
    for sen in unique_value:
        if sen is np.nan:
            trans_dic[sen] = sen
            continue

        non_alpha_chars = re.sub(r'\W+', '', sen)
        non_alpha_chars = re.search(r'[^a-zA-Z0-9]', non_alpha_chars)

        if non_alpha_chars:
            changed_chars = translator.translate(sen, dest='en').text 
            trans_dic[sen] = changed_chars
        
    return trans_dic

def to_english(df,col):
    # en_dic에 있는 값이면 해당 행 값을 사전의 값으로 교체
    df[col] = df[col].apply(lambda x: dic[x] if x in dic else x)

def preprocess_str(col):
    pre_train[col] = pre_train[col].str.lower()
    pre_test[col] = pre_test[col].str.lower()
    
    mask_train = pre_train[col].notnull()
    mask_test = pre_test[col].notnull()
    pre_train.loc[mask_train, col] = pre_train.loc[mask_train, col].apply(lambda x: x.replace(" ", ""))
    pre_test.loc[mask_test, col] = pre_test.loc[mask_test, col].apply(lambda x: x.replace(" ", "")) 

#//india// 등 손실되는 데이터 존재. -> 전처리 방법 수정
def process_country(country):
    result = np.nan
    
    if pd.isna(country):
        return np.nan
    
    parts = [x for x in country.split('/') if x != '']
    
    if len(parts) >= 1:
        result = parts[-1]
    else:
        return np.nan
    
    if '@' in str(result):
        return np.nan
        
    return result


# 묶을 수 있는 직업은 처리. 세분화 되어있더라도 모델에게는 아예 다른 직업으로 인식될 것.
def preprocess_job(job):
    if pd.isna(job):
        return np.nan
    
    if 'direct' in job:
        return 'director'
    elif 'consult' in job:
        return 'consultant'
    elif 'owner' in job:
        return 'owner'
    elif 'market' in job:
        return 'marketor'
    elif 'account' in job:
        return 'account'
    elif 'manage' in job:
        return 'manager'
    elif 'admin' in job:
        return 'administrator'
    elif 'design' in job:
        return 'designer'
    elif 'engineer' in job:
        return 'engineer'
    elif 'manager' in job:
        return 'manager'
    elif 'sales' in job:
        return 'sales'
    elif 'research' in job:
        return 'research'
    elif 'support' in job:
        return 'support'
    elif 'consultant' in job:
        return 'consultant'
    elif 'finance' in job:
        return 'finance'
    elif 'sale' in job:
        return 'sales'
    elif 'educat' or 'teach' in job:
        return 'educator'
    elif 'healthcare'in job:
        return 'healthcare'
    elif 'human' or 'hr posting' in job:
        return 'hr'
    elif 'inform' in job:
        return 'it'
    elif 'military' in job:
        return 'military'
    elif 'comunica' in job:
        return 'comunicator'
    else:
        return job

In [11]:
print(len(pre_train['product_category'].unique()))

358

In [12]:
need_to_en = ['customer_job' , 'inquiry_type' , 'product_category' , 'product_subcategory' , 'product_modelname']
for n in need_to_en:
    dic = en_dic(pre_train,n)
    to_english(pre_train,n)
    
for n in need_to_en:
    dic = en_dic(pre_test,n)
    to_english(pre_test,n)
    
for n in object_columns:
    preprocess_str(n)

pre_train['customer_country'] = pre_train['customer_country'].apply(process_country)
pre_test['customer_country'] = pre_test['customer_country'].apply(process_country)
pre_train['customer_country'] = pre_train['customer_country'].replace("us", "unitedstates")
pre_test['customer_country'] = pre_test['customer_country'].replace("us", "unitedstates")

pre_train['customer_job'].fillna(0)
pre_train['customer_job'] = pre_train['customer_job'].apply(preprocess_job)
pre_test['customer_job'] = pre_test['customer_job'].apply(preprocess_job)
                                                                        
# 'inquiry_type', 'customer_position', 'customer_type' 열에서 특정 문자열을 'other'로 대체
columns_to_replace_other = ['inquiry_type', 'customer_position', 'customer_type','product_category']
for col in columns_to_replace_other:
    pre_train[col] = pre_train[col].replace(['other','other_', 'etc.', 'others'], 'other')
    pre_test[col] = pre_test[col].replace(['other','other_', 'etc.', 'others'], 'other')

## product_category를 통한 증강 및 text 전처리

여러 카테고리를 가진 값을 , 기준으로 분해 -> 증강

In [13]:
pre_train[pre_train['product_category'] == 'monior/monitortv,tv,commercialtv,pc,refrigerator,solar,rac,washingmachine,mobile,ess,audio/video']

,bant_submit,customer_country,business_unit,com_reg_ver_win_rate,customer_idx,customer_type,enterprise,historical_existing_cnt,id_strategic_ver,it_strategic_ver,idit_strategic_ver,customer_job,lead_desc_length,inquiry_type,product_category,product_subcategory,product_modelname,customer_position,response_corporate,expected_timeline,ver_cus,ver_pro,ver_win_rate_x,ver_win_ratio_per_bu,business_area,business_subarea,lead_owner,is_converted
22696,1.0,nigeria,solution,NaN,25309,NaN,enterprise,NaN,0,0,0,educator,18,requestforquotationorpurchase,"monior/monitortv,tv,commercialtv,pc,refrigerat...",NaN,NaN,other,lgekr,9months~1year,0,0,0.000543,NaN,specialpurpose,NaN,441,False

In [14]:
# 'product_category' 열의 각 값을 쉼표로 분할합니다.
pre_train['product_category'] = pre_train['product_category'].str.split(',')

# explode 함수를 사용하여 각 분할된 값을 별도의 행으로 만듭니다.
pre_train = pre_train.explode('product_category')

In [15]:
pre_train.loc[22696]

,bant_submit,customer_country,business_unit,com_reg_ver_win_rate,customer_idx,customer_type,enterprise,historical_existing_cnt,id_strategic_ver,it_strategic_ver,idit_strategic_ver,customer_job,lead_desc_length,inquiry_type,product_category,product_subcategory,product_modelname,customer_position,response_corporate,expected_timeline,ver_cus,ver_pro,ver_win_rate_x,ver_win_ratio_per_bu,business_area,business_subarea,lead_owner,is_converted
22696,1.0,nigeria,solution,NaN,25309,NaN,enterprise,NaN,0,0,0,educator,18,requestforquotationorpurchase,monior/monitortv,NaN,NaN,other,lgekr,9months~1year,0,0,0.000543,NaN,specialpurpose,NaN,441,False
22696,1.0,nigeria,solution,NaN,25309,NaN,enterprise,NaN,0,0,0,educator,18,requestforquotationorpurchase,tv,NaN,NaN,other,lgekr,9months~1year,0,0,0.000543,NaN,specialpurpose,NaN,441,False
22696,1.0,nigeria,solution,NaN,25309,NaN,enterprise,NaN,0,0,0,educator,18,requestforquotationorpurchase,commercialtv,NaN,NaN,other,lgekr,9months~1year,0,0,0.000543,NaN,specialpurpose,NaN,441,False
22696,1.0,nigeria,solution,NaN,25309,NaN,enterprise,NaN,0,0,0,educator,18,requestforquotationorpurchase,pc,NaN,NaN,other,lgekr,9months~1year,0,0,0.000543,NaN,specialpurpose,NaN,441,False
22696,1.0,nigeria,solution,NaN,25309,NaN,enterprise,NaN,0,0,0,educator,18,requestforquotationorpurchase,refrigerator,NaN,NaN,other,lgekr,9months~1year,0,0,0.000543,NaN,specialpurpose,NaN,441,False
22696,1.0,nigeria,solution,NaN,25309,NaN,enterprise,NaN,0,0,0,educator,18,requestforquotationorpurchase,solar,NaN,NaN,other,lgekr,9months~1year,0,0,0.000543,NaN,specialpurpose,NaN,441,False
22696,1.0,nigeria,solution,NaN,25309,NaN,enterprise,NaN,0,0,0,educator,18,requestforquotationorpurchase,rac,NaN,NaN,other,lgekr,9months~1year,0,0,0.000543,NaN,specialpurpose,NaN,441,False
22696,1.0,nigeria,solution,NaN,25309,NaN,enterprise,NaN,0,0,0,educator,18,requestforquotationorpurchase,washingmachine,NaN,NaN,other,lgekr,9months~1year,0,0,0.000543,NaN,specialpurpose,NaN,441,False
22696,1.0,nigeria,solution,NaN,25309,NaN,enterprise,NaN,0,0,0,educator,18,requestforquotationorpurchase,mobile,NaN,NaN,other,lgekr,9months~1year,0,0,0.000543,NaN,specialpurpose,NaN,441,False
22696,1.0,nigeria,solution,NaN,25309,NaN,enterprise,NaN,0,0,0,educator,18,requestforquotationorpurchase,ess,NaN,NaN,other,lgekr,9months~1year,0,0,0.000543,NaN,specialpurpose,NaN,441,False
22696,1.0,nigeria,solution,NaN,25309,NaN,enterprise,NaN,0,0,0,educator,18,requestforquotationorpurchase,audio/video,NaN,NaN,other,lgekr,9months~1year,0,0,0.000543,NaN,specialpurpose,NaN,441,False

In [16]:
print(pre_train['product_category'].unique())

['multi-split' 'single-split' 'vrf' 'chiller' 'other' 'rac'
 'tetooucasseteinverter' nan 'softwaresolution' 'alllgvrfsystems'
 'ventilation' 'athermodynamicwaterheater' 'residentialairconditioner'
 'outros' 'heating' 'multiv5vrf' 'splittunggal' 'multiinverter'
 'standardsignage' 'highbrightnesssignage' 'interactivesignage'
 'videowallsignage' 'ledsignage' 'hoteltv' 'signagecaresolution'
 'oledsignage' 'idb' 'videowall' 'one:quickseries' 'commercialtv'
 'lgone:quick' 'specialsignage' 'accessories' 'commercialdisplay'
 'interactivedigitalboard' 'standard' 'uhdsignage' 'smarttvsignage'
 'lgone:quickseries' 'pro:centric' 'ur640' 'ur640s' 'webos'
 'signagecaresolutions' 'aio|onequick' 'highbrightness' 'hospitaltv'
 'digitalsignage' 'monitor' 'pc' 'laptop' 'projector' 'clouddevice'
 'medicaldisplay' 'washingmachine' 'dryer' 'solar' 'systemac'
 'monitorsignage' 'monior/monitortv' 'aircare' 'built-in/cooking' 'tv'
 'ess' 'robot' 'ems' 'chill' 'audio/video' 'ultrastretchseries'
 'interactivedisplay' 'leddisplay' 'onequickworks' 'fhdseries'
 'onequickseries' 'standarddisplay' '43us660h0sd.awz' '50uq801c0sb.bwz'
 'onequick:flex' 'ledaio136' '110+videowall' 'aio' 'robots'
 'one:quickflex' 'tvsignage' 'collaborationdisplays' 'oleddisplay' 'id'
 'meeting&screensharedirectviewleddirectviewled' 'windowfacingdisplay'
 'lgcustomercareprogram' 'led' 'lainnya' 'multiv' 'control'
 'residentialairconditioners' 'pendingin' 'multiv5air'
 'arcondicionadoresidencial' 'multivwater5' 'singlesplit' 'ahu'
 'multisplit' 'lghomeblissairsolution' 'lgparadiseairsolution'
 'technicalsupport' 'airconditioners' 'salesinquiry' 'multiplesplitting'
 'conditioningandcooling' 'error' 'medicaldisplays' '28mq780'
 'computermonitors' 'monitor&pc' 'medicalmonitors' 'systemairconditioner'
 'mobile' 'watercare' 'energystoragesystem' 'refrigerator' 'vacuumcleaner'
 'homebeauty' 'audio' 'videwall' 'ultrastretchsignage'
 'digitalsignageorcommercialtvs' 'educationcreateboard'
 'virtualproduction' 'laec015' '55us660h0sd.bwz' 'transparentoled'
 'medical-surgical' 'radiologydisplays' 'highinch86/98or110' 'leadallin'
 'informationdisplay' 'taalcdlfddisplays' 'rac/cac' 'heatingsolutions'
 'otros' 'built' 'styler' 'audio/' 'sac' 'laec015-gn.awz' 'gscd046'
 '32lq621cbsb.awz' '43uh5f-h.awzm' '49vl5g-m.awzm' '55uq801c0sb.bwz'
 '43uq751c0sf.bwz' '32/43pol' 'htv' '43uq751c0sb.bwz' '49uh/49xf'
 '50us660h0sd.bwz' 'tv60"' 'medicalmonitor' 'washingmach' 'unitario' 'cac'
 'singlepackage' 'multicentralairconditioner' 'heating(heatpumps)'
 'cooler' 'householdairconditioner' 'variableflowsystemvrf'
 'chiller/enfriadoras' '49vl5g-m' 'lgledbloc' 'uh' '55vm5e-a' 'laec15'
 '55vm5j-h' '49vl5f' 'standalone' 'corpouh5f' 'ledallinone'
 'monitorindustrial_rmk' 'lgmagnit' 'specialdisplay' 'signage'
 'videowall_rmk' 'bu50nst' 'led70m2' 'ledcinema' '86uh5f' '55tc3d'
 '43us660h(na)' 'procentrichotel' 'videowall+aio' 'hospitality'
 'one:quick' 'highbrightnessdisplay' 'comercialtv' 'corpuh5f-'
 'allinone_rmk' 'hoteleria_us670h' 'retaildigital' 'software' 'ctv'
 'autre' 'vb.' 'acrumah' 'aireacondicionadoresidencial' 'vrf-multivs'
 'variablerefrigerantflow(drv)systems' 'multi-split(severalpieces)'
 'aquecimento' 'lgsalangairsolutionfordreamhomes' 'racsinglecac'
 'services' 'last' 'etc.' 'onorseveralreversibleac' 'scrollcompressor'
 'pantallaledoutdoor' 'klimatyzacjamulti-split' 'notspecified' 'singlecac'
 'kimatyzacjavrf' '55svh7f-a' 'tr3' '98uh5e' 'inne'
 'vrfcentralairconditioner' 'smarttv' 'tv55"' 'surgicalmonitor' 'gsca046'
 'gscd100' 'procentric' '32pol' 'tv43pol' '43pol' '' 'adefinir'
 'centralairconditionerchiller' 'localairconditioning' 'lsca039'
 'essentialseries' 'parts']

In [17]:
pre_train[pre_train['product_category']=='']

,bant_submit,customer_country,business_unit,com_reg_ver_win_rate,customer_idx,customer_type,enterprise,historical_existing_cnt,id_strategic_ver,it_strategic_ver,idit_strategic_ver,customer_job,lead_desc_length,inquiry_type,product_category,product_subcategory,product_modelname,customer_position,response_corporate,expected_timeline,ver_cus,ver_pro,ver_win_rate_x,ver_win_ratio_per_bu,business_area,business_subarea,lead_owner,is_converted
58345,0.75,russia,solution,NaN,46969,NaN,enterprise,NaN,0,0,0,educator,295,requestfortechnicalconsulting,,NaN,NaN,manager,lgekr,morethanayear,0,0,0.000717,NaN,hotel&accommodation,NaN,441,False

In [18]:
def preprocess_pro_category(category):
    if pd.isna(category):
        return np.nan
    
    if 'signage' in category or 'awzm' in category or 'lgledbloc' in category or 'gsca' in category or 'gscd' in category or 'lsca039' in category:
        return 'signage'
    elif 'awz' in category or 'bwz' in category or 'hoteltv' in category or 'commercialtv' in category or 'hospitaltv' in category or 'monior/monitortv' in category or 'tvsignage' in category or 'digitalsignageorcommercialtvs' in category or 'htv' in category or 'tv60' in category or 'comercialtv' in category or 'ctv' in category or 'smarttv' in category or 'tv55' in category or 'tv43pol' in category or 'ur640' in category or 'ur640s' in category or '43us660h0sd.awz' in category or '50uq801c0sb.bwz' in category or 'uh' in category or 'vl' in category or 'highinch86/98or110' in category or '43us660h' in category or 'hoteleria_us670h' in category:
        return 'tv'
    elif 'cac' in category or 'sac' in category or 'vrfcentralairconditioner' in category or 'residentialairconditioner' in category or 'systemac' in category or 'onorseveralreversibleac' in category or 'aireacondicionadoresidencial' in category:
        return 'ac'
    elif 'vrf' in category or 'variablerefrigerantflow(drv)systems' in category:
        return 'vrf'
    elif 'wall' in category or '49vl5g' in category or 'vm' in category or '55svh7f-a' in category:
        return 'videowall'
    elif 'centric' in category:
        return 'procentric'
    elif 'pol' in category or 'monitor' in category or '28mq780' in category or '55tc3d' in category:
        return 'monitor'
    elif 'multiv' in category:
        return 'multiv'
    elif 'display' in category:
        return 'display'
    elif 'audio' in category:
        return 'audio'
    elif 'aio' in category:
        return 'aio'
    elif 'led' in category or 'gscd046' in category or 'laec' in category:
        return 'led'
    elif 'chill' in category:
        return 'chiller'
    elif 'one' in category and 'quick' in category:
        return 'one-quick'
    elif 'washing' in category:
        return 'washingmachine'
    elif 'multi' in category and 'split' in category:
        return 'multi-split'
    elif 'single' in category and 'split' in category:
        return 'single-split'
    elif 'bu50nst' in category:
        return 'projector'
    elif 'board' in category or 'tr3' in category:
        return 'board'
    elif 'airsolution' in category or 'acrumah' in category:
        return 'airsolution'
    elif 'etc.' in category:
        return 'other'
    else: 
        return category
    
pre_train['product_category'] = pre_train['product_category'].apply(preprocess_pro_category)
pre_test['product_category'] = pre_test['product_category'].apply(preprocess_pro_category)

print(pre_train['product_category'].unique())

['multi-split' 'single-split' 'vrf' 'chiller' 'other' 'rac'
 'tetooucasseteinverter' nan 'softwaresolution' 'ventilation'
 'athermodynamicwaterheater' 'ac' 'outros' 'heating' 'splittunggal'
 'multiinverter' 'signage' 'tv' 'idb' 'videowall' 'one-quick'
 'accessories' 'display' 'board' 'standard' 'procentric' 'webos' 'aio'
 'highbrightness' 'monitor' 'pc' 'laptop' 'projector' 'clouddevice'
 'washingmachine' 'dryer' 'solar' 'aircare' 'built-in/cooking' 'ess'
 'robot' 'ems' 'audio' 'ultrastretchseries' 'fhdseries' 'robots' 'id'
 'lgcustomercareprogram' 'led' 'lainnya' 'multiv' 'control' 'pendingin'
 'arcondicionadoresidencial' 'ahu' 'airsolution' 'technicalsupport'
 'airconditioners' 'salesinquiry' 'conditioningandcooling' 'error'
 'systemairconditioner' 'mobile' 'watercare' 'energystoragesystem'
 'refrigerator' 'vacuumcleaner' 'homebeauty' 'virtualproduction'
 'medical-surgical' 'leadallin' 'heatingsolutions' 'otros' 'built'
 'styler' 'unitario' 'singlepackage' 'multicentralairconditioner'
 'heating(heatpumps)' 'cooler' 'householdairconditioner' 'standalone'
 'lgmagnit' 'hospitality' 'allinone_rmk' 'retaildigital' 'software'
 'autre' 'vb.' 'aquecimento' 'services' 'last' 'scrollcompressor'
 'notspecified' 'inne' '' 'adefinir' 'localairconditioning'
 'essentialseries' 'parts']

In [19]:
pre_train = pre_train[pre_train['product_category'] != '']

In [20]:
pre_train.loc[22696]

,bant_submit,customer_country,business_unit,com_reg_ver_win_rate,customer_idx,customer_type,enterprise,historical_existing_cnt,id_strategic_ver,it_strategic_ver,idit_strategic_ver,customer_job,lead_desc_length,inquiry_type,product_category,product_subcategory,product_modelname,customer_position,response_corporate,expected_timeline,ver_cus,ver_pro,ver_win_rate_x,ver_win_ratio_per_bu,business_area,business_subarea,lead_owner,is_converted
22696,1.0,nigeria,solution,NaN,25309,NaN,enterprise,NaN,0,0,0,educator,18,requestforquotationorpurchase,tv,NaN,NaN,other,lgekr,9months~1year,0,0,0.000543,NaN,specialpurpose,NaN,441,False
22696,1.0,nigeria,solution,NaN,25309,NaN,enterprise,NaN,0,0,0,educator,18,requestforquotationorpurchase,tv,NaN,NaN,other,lgekr,9months~1year,0,0,0.000543,NaN,specialpurpose,NaN,441,False
22696,1.0,nigeria,solution,NaN,25309,NaN,enterprise,NaN,0,0,0,educator,18,requestforquotationorpurchase,tv,NaN,NaN,other,lgekr,9months~1year,0,0,0.000543,NaN,specialpurpose,NaN,441,False
22696,1.0,nigeria,solution,NaN,25309,NaN,enterprise,NaN,0,0,0,educator,18,requestforquotationorpurchase,pc,NaN,NaN,other,lgekr,9months~1year,0,0,0.000543,NaN,specialpurpose,NaN,441,False
22696,1.0,nigeria,solution,NaN,25309,NaN,enterprise,NaN,0,0,0,educator,18,requestforquotationorpurchase,refrigerator,NaN,NaN,other,lgekr,9months~1year,0,0,0.000543,NaN,specialpurpose,NaN,441,False
22696,1.0,nigeria,solution,NaN,25309,NaN,enterprise,NaN,0,0,0,educator,18,requestforquotationorpurchase,solar,NaN,NaN,other,lgekr,9months~1year,0,0,0.000543,NaN,specialpurpose,NaN,441,False
22696,1.0,nigeria,solution,NaN,25309,NaN,enterprise,NaN,0,0,0,educator,18,requestforquotationorpurchase,rac,NaN,NaN,other,lgekr,9months~1year,0,0,0.000543,NaN,specialpurpose,NaN,441,False
22696,1.0,nigeria,solution,NaN,25309,NaN,enterprise,NaN,0,0,0,educator,18,requestforquotationorpurchase,washingmachine,NaN,NaN,other,lgekr,9months~1year,0,0,0.000543,NaN,specialpurpose,NaN,441,False
22696,1.0,nigeria,solution,NaN,25309,NaN,enterprise,NaN,0,0,0,educator,18,requestforquotationorpurchase,mobile,NaN,NaN,other,lgekr,9months~1year,0,0,0.000543,NaN,specialpurpose,NaN,441,False
22696,1.0,nigeria,solution,NaN,25309,NaN,enterprise,NaN,0,0,0,educator,18,requestforquotationorpurchase,ess,NaN,NaN,other,lgekr,9months~1year,0,0,0.000543,NaN,specialpurpose,NaN,441,False
22696,1.0,nigeria,solution,NaN,25309,NaN,enterprise,NaN,0,0,0,educator,18,requestforquotationorpurchase,audio,NaN,NaN,other,lgekr,9months~1year,0,0,0.000543,NaN,specialpurpose,NaN,441,False

In [21]:
pre_train.drop_duplicates(inplace=True)

In [22]:
pre_train.loc[58345]

,bant_submit,customer_country,business_unit,com_reg_ver_win_rate,customer_idx,customer_type,enterprise,historical_existing_cnt,id_strategic_ver,it_strategic_ver,idit_strategic_ver,customer_job,lead_desc_length,inquiry_type,product_category,product_subcategory,product_modelname,customer_position,response_corporate,expected_timeline,ver_cus,ver_pro,ver_win_rate_x,ver_win_ratio_per_bu,business_area,business_subarea,lead_owner,is_converted
58345,0.75,russia,solution,NaN,46969,NaN,enterprise,NaN,0,0,0,educator,295,requestfortechnicalconsulting,tv,NaN,NaN,manager,lgekr,morethanayear,0,0,0.000717,NaN,hotel&accommodation,NaN,441,False
58345,0.75,russia,solution,NaN,46969,NaN,enterprise,NaN,0,0,0,educator,295,requestfortechnicalconsulting,solar,NaN,NaN,manager,lgekr,morethanayear,0,0,0.000717,NaN,hotel&accommodation,NaN,441,False
58345,0.75,russia,solution,NaN,46969,NaN,enterprise,NaN,0,0,0,educator,295,requestfortechnicalconsulting,ess,NaN,NaN,manager,lgekr,morethanayear,0,0,0.000717,NaN,hotel&accommodation,NaN,441,False
58345,0.75,russia,solution,NaN,46969,NaN,enterprise,NaN,0,0,0,educator,295,requestfortechnicalconsulting,pc,NaN,NaN,manager,lgekr,morethanayear,0,0,0.000717,NaN,hotel&accommodation,NaN,441,False
58345,0.75,russia,solution,NaN,46969,NaN,enterprise,NaN,0,0,0,educator,295,requestfortechnicalconsulting,projector,NaN,NaN,manager,lgekr,morethanayear,0,0,0.000717,NaN,hotel&accommodation,NaN,441,False
58345,0.75,russia,solution,NaN,46969,NaN,enterprise,NaN,0,0,0,educator,295,requestfortechnicalconsulting,robot,NaN,NaN,manager,lgekr,morethanayear,0,0,0.000717,NaN,hotel&accommodation,NaN,441,False
58345,0.75,russia,solution,NaN,46969,NaN,enterprise,NaN,0,0,0,educator,295,requestfortechnicalconsulting,ac,NaN,NaN,manager,lgekr,morethanayear,0,0,0.000717,NaN,hotel&accommodation,NaN,441,False
58345,0.75,russia,solution,NaN,46969,NaN,enterprise,NaN,0,0,0,educator,295,requestfortechnicalconsulting,ems,NaN,NaN,manager,lgekr,morethanayear,0,0,0.000717,NaN,hotel&accommodation,NaN,441,False
58345,0.75,russia,solution,NaN,46969,NaN,enterprise,NaN,0,0,0,educator,295,requestfortechnicalconsulting,rac,NaN,NaN,manager,lgekr,morethanayear,0,0,0.000717,NaN,hotel&accommodation,NaN,441,False
58345,0.75,russia,solution,NaN,46969,NaN,enterprise,NaN,0,0,0,educator,295,requestfortechnicalconsulting,chiller,NaN,NaN,manager,lgekr,morethanayear,0,0,0.000717,NaN,hotel&accommodation,NaN,441,False
58345,0.75,russia,solution,NaN,46969,NaN,enterprise,NaN,0,0,0,educator,295,requestfortechnicalconsulting,refrigerator,NaN,NaN,manager,lgekr,morethanayear,0,0,0.000717,NaN,hotel&accommodation,NaN,441,False

In [23]:
print(len(pre_train['product_category'].unique()))

99

## 스케일링

In [24]:
features = ['com_reg_ver_win_rate','lead_desc_length','ver_win_ratio_per_bu','historical_existing_cnt']

print(pre_train[features].min())
print(pre_train[features].max())

com_reg_ver_win_rate       0.003788
lead_desc_length           1.000000
ver_win_ratio_per_bu       0.011583
historical_existing_cnt    0.000000
dtype: float64
com_reg_ver_win_rate          1.000000
lead_desc_length           1264.000000
ver_win_ratio_per_bu          0.285714
historical_existing_cnt    1394.000000
dtype: float64

In [25]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

pre_train[features] = scaler.fit_transform(pre_train[features]) # fit_transform
pre_test[features] = scaler.transform(pre_test[features]) # transform

In [26]:
print(pre_train[features].min())
print(pre_train[features].max())

com_reg_ver_win_rate       0.0
lead_desc_length           0.0
ver_win_ratio_per_bu       0.0
historical_existing_cnt    0.0
dtype: float64
com_reg_ver_win_rate       1.0
lead_desc_length           1.0
ver_win_ratio_per_bu       1.0
historical_existing_cnt    1.0
dtype: float64

In [27]:
pre_train[features].head()

,com_reg_ver_win_rate,lead_desc_length,ver_win_ratio_per_bu,historical_existing_cnt
0,0.063118,0.048298,0.055676,NaN
1,0.063118,0.075218,0.055676,0.008608
2,0.085425,0.043547,0.055676,0.103300
3,0.085425,0.034046,0.055676,NaN
4,0.085425,0.076010,0.055676,NaN

In [28]:
pre_train.iloc[[1,2]]

,bant_submit,customer_country,business_unit,com_reg_ver_win_rate,customer_idx,customer_type,enterprise,historical_existing_cnt,id_strategic_ver,it_strategic_ver,idit_strategic_ver,customer_job,lead_desc_length,inquiry_type,product_category,product_subcategory,product_modelname,customer_position,response_corporate,expected_timeline,ver_cus,ver_pro,ver_win_rate_x,ver_win_ratio_per_bu,business_area,business_subarea,lead_owner,is_converted
1,1.0,philippines,as,0.063118,23122,end-customer,enterprise,0.008608,0,0,0,educator,0.075218,quotationorpurchaseconsultation,multi-split,NaN,NaN,ceo/founder,lgeph,lessthan3months,1,0,0.003079,0.055676,corporate/office,advertising,1,True
2,1.0,india,as,0.085425,1755,end-customer,enterprise,0.103300,0,0,0,engineer,0.043547,productinformation,single-split,NaN,NaN,partner,lgeil,lessthan3months,1,0,0.003079,0.055676,corporate/office,construction,2,True

## 3. 모델 학습

### 모델 학습

In [29]:
# Stratified K-Fold 교차 검증 설정
n_splits = 5  # 원하는 Fold 수
skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=42)

# 최적의 하이퍼파라미터 설정
best_params = {'depth': 10, 'iterations': 1500, 'learning_rate': 0.01}

# 교차 검증 수행 및 평가 지표 저장
macro_f1_scores = []
models = []
best_f1_score = 0

resetIndex_train = pre_train.reset_index(drop=True)

train_x = resetIndex_train.drop(columns=['is_converted'])
train_y = resetIndex_train['is_converted'].astype(int)
train_x = train_x.fillna(0)

class_weights = compute_class_weight('balanced', classes=[0, 1], y=train_y)

for train_index, valid_index in skf.split(train_x, train_y):
    print(train_index)
    print(valid_index)
    X_train, X_valid = train_x.iloc[train_index], train_x.iloc[valid_index]
    y_train, y_valid = train_y[train_index], train_y[valid_index]

    # CatBoost 모델 생성 및 학습
    model = CatBoostClassifier(loss_function='Logloss', cat_features=np.where(pre_train.dtypes == np.object)[0], eval_metric='F1', 
                               random_seed=42, verbose=500, **best_params, class_weights = {0:class_weights[0], 1:class_weights[1]})
    
    model.fit(X_train, y_train, eval_set=[(X_valid,y_valid)])

    # 검증 데이터에 대한 예측 및 평가 (Macro F1 Score)
    valid_predictions = model.predict(X_valid)
    
    print(valid_predictions)
    print(y_valid[:5])
    macro_f1 = f1_score(y_valid, valid_predictions, average='macro')
    macro_f1_scores.append(macro_f1)
    models.append(model)

    if macro_f1 > best_f1_score:
        best_f1_score = macro_f1
        best_classification_model = model
        y_val = y_valid
        pred_val = valid_predictions

# Macro F1 Score 출력
print("Macro F1 Scores:", macro_f1_scores)

[    0     1     2 ... 53565 53566 53567]
[    4     8    10 ... 53542 53544 53557]

/tmp/ipykernel_76/366239352.py:28: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  model = CatBoostClassifier(loss_function='Logloss', cat_features=np.where(pre_train.dtypes == np.object)[0], eval_metric='F1',

0:	learn: 0.8405669	test: 0.8658717	best: 0.8658717 (0)	total: 186ms	remaining: 4m 38s
500:	learn: 0.9656284	test: 0.9433545	best: 0.9439890 (474)	total: 1m 28s	remaining: 2m 55s
1000:	learn: 0.9794668	test: 0.9431327	best: 0.9449526 (895)	total: 2m 51s	remaining: 1m 25s
1499:	learn: 0.9852285	test: 0.9409806	best: 0.9449526 (895)	total: 4m 14s	remaining: 0us

bestTest = 0.9449525869
bestIteration = 895

Shrink model to first 896 iterations.
[1 1 1 ... 0 0 0]
4     1
8     1
10    1
18    0
19    0
Name: is_converted, dtype: int64
[    2     3     4 ... 53564 53566 53567]
[    0     1     6 ... 53561 53562 53565]

/tmp/ipykernel_76/366239352.py:28: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  model = CatBoostClassifier(loss_function='Logloss', cat_features=np.where(pre_train.dtypes == np.object)[0], eval_metric='F1',

0:	learn: 0.8800916	test: 0.8707934	best: 0.8707934 (0)	total: 177ms	remaining: 4m 25s
500:	learn: 0.9654216	test: 0.9349900	best: 0.9355388 (491)	total: 1m 26s	remaining: 2m 52s
1000:	learn: 0.9773339	test: 0.9367554	best: 0.9374270 (779)	total: 2m 46s	remaining: 1m 23s
1499:	learn: 0.9809319	test: 0.9367798	best: 0.9380412 (1220)	total: 3m 50s	remaining: 0us

bestTest = 0.9380412268
bestIteration = 1220

Shrink model to first 1221 iterations.
[0 1 1 ... 0 0 0]
0     1
1     1
6     1
11    1
13    1
Name: is_converted, dtype: int64
[    0     1     3 ... 53565 53566 53567]
[    2     5    12 ... 53554 53555 53563]

/tmp/ipykernel_76/366239352.py:28: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  model = CatBoostClassifier(loss_function='Logloss', cat_features=np.where(pre_train.dtypes == np.object)[0], eval_metric='F1',

0:	learn: 0.8786846	test: 0.8795649	best: 0.8795649 (0)	total: 145ms	remaining: 3m 36s
500:	learn: 0.9641198	test: 0.9464121	best: 0.9469962 (475)	total: 1m 26s	remaining: 2m 52s
1000:	learn: 0.9782065	test: 0.9464065	best: 0.9497281 (749)	total: 2m 51s	remaining: 1m 25s
1499:	learn: 0.9853596	test: 0.9425377	best: 0.9497281 (749)	total: 4m 20s	remaining: 0us

bestTest = 0.9497281459
bestIteration = 749

Shrink model to first 750 iterations.
[1 1 1 ... 0 0 0]
2     1
5     1
12    1
17    1
21    0
Name: is_converted, dtype: int64
[    0     1     2 ... 53563 53564 53565]
[    3     7     9 ... 53552 53566 53567]

/tmp/ipykernel_76/366239352.py:28: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  model = CatBoostClassifier(loss_function='Logloss', cat_features=np.where(pre_train.dtypes == np.object)[0], eval_metric='F1',

0:	learn: 0.8300865	test: 0.8528019	best: 0.8528019 (0)	total: 36.7ms	remaining: 55s
500:	learn: 0.9658123	test: 0.9489881	best: 0.9495211 (477)	total: 1m 26s	remaining: 2m 52s
1000:	learn: 0.9777585	test: 0.9485641	best: 0.9507438 (592)	total: 2m 48s	remaining: 1m 24s
1499:	learn: 0.9829778	test: 0.9469950	best: 0.9507438 (592)	total: 4m	remaining: 0us

bestTest = 0.9507437921
bestIteration = 592

Shrink model to first 593 iterations.
[1 1 1 ... 0 0 0]
3     1
7     1
9     1
16    1
27    0
Name: is_converted, dtype: int64
[    0     1     2 ... 53565 53566 53567]
[   15    23    24 ... 53556 53558 53564]

/tmp/ipykernel_76/366239352.py:28: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  model = CatBoostClassifier(loss_function='Logloss', cat_features=np.where(pre_train.dtypes == np.object)[0], eval_metric='F1',

0:	learn: 0.8324839	test: 0.8446759	best: 0.8446759 (0)	total: 45.6ms	remaining: 1m 8s
500:	learn: 0.9631788	test: 0.9412848	best: 0.9426712 (278)	total: 1m 24s	remaining: 2m 49s
1000:	learn: 0.9767604	test: 0.9399179	best: 0.9426712 (278)	total: 2m 42s	remaining: 1m 21s
1499:	learn: 0.9818422	test: 0.9385035	best: 0.9426712 (278)	total: 3m 55s	remaining: 0us

bestTest = 0.9426711662
bestIteration = 278

Shrink model to first 279 iterations.
[1 0 0 ... 0 0 0]
15    1
23    0
24    0
31    0
37    0
Name: is_converted, dtype: int64
Macro F1 Scores: [0.8795123151888429, 0.8880624663192428, 0.8846911690049302, 0.882465421744208, 0.8617982549412312]

In [30]:
def get_clf_eval(y_test, y_pred=None):
    confusion = confusion_matrix(y_test, y_pred, labels=[1, 0])
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, labels=[True, False])
    recall = recall_score(y_test, y_pred)
    F1 = f1_score(y_test, y_pred, labels=[True, False])

    print("오차행렬:\n", confusion)
    print("\n정확도: {:.4f}".format(accuracy))
    print("정밀도: {:.4f}".format(precision))
    print("재현율: {:.4f}".format(recall))
    print("F1: {:.4f}".format(F1))

In [31]:
get_clf_eval(y_val, pred_val)

오차행렬:
 [[ 831   78]
 [ 343 9462]]

정확도: 0.9607
정밀도: 0.7078
재현율: 0.9142
F1: 0.7979

## 4. 제출하기

### 테스트 데이터 예측

customer_job , inquiry_type , product_category , product_subcategory , product_modelname

In [32]:
pre_test['customer_job'].unique()

array(['consultant', nan, 'educator', 'sales', 'engineer', 'marketor',
       'support', 'finance', 'administrator', 'manager', 'designer',
       'account', 'research'], dtype=object)

In [33]:
for n in columns_categorized:
    pre_test[n] = pre_test[n].fillna(0)
    pre_test[n] = pre_test[n].astype('int').astype('object')

In [34]:
# 예측에 필요한 데이터 분리
x_test = pre_test.drop(["is_converted"], axis=1)
x_test.head()

,bant_submit,customer_country,business_unit,com_reg_ver_win_rate,customer_idx,customer_type,enterprise,historical_existing_cnt,id_strategic_ver,it_strategic_ver,idit_strategic_ver,customer_job,lead_desc_length,inquiry_type,product_category,product_subcategory,product_modelname,customer_position,response_corporate,expected_timeline,ver_cus,ver_pro,ver_win_rate_x,ver_win_ratio_per_bu,business_area,business_subarea,lead_owner
0,0.00,brazil,id,0.069725,47466,endcustomer,enterprise,0.038020,0,0,0,consultant,0.001584,NaN,NaN,NaN,NaN,none,lgesp,NaN,1,0,0.001183,0.139558,retail,electronics&telco,278
1,0.25,unitedstates,it,NaN,5405,endcustomer,smb,NaN,0,0,0,NaN,0.017419,quotationorpurchaseconsultation,NaN,NaN,NaN,none,lgeus,NaN,0,0,0.000013,NaN,transportation,others,437
2,1.00,u.a.e,id,NaN,13597,specifier/influencer,smb,NaN,0,0,0,educator,0.108472,quotationorpurchaseconsultation,tv,ut662mseries,50ut662m(mea),manager,lgegf,lessthan3months,0,0,0.000060,0.436158,hospital&healthcare,generalhospital,874
3,0.50,unitedstates,id,0.115293,17204,NaN,enterprise,NaN,0,0,0,sales,0.001584,quotationorpurchaseconsultation,NaN,digitalsignageorcommercialtvs,NaN,none,lgeus,morethanayear,0,0,0.001183,0.139558,retail,NaN,194
4,1.00,brazil,id,0.071431,2329,endcustomer,enterprise,0.001435,1,0,1,engineer,0.083927,quotationorpurchaseconsultation,signage,lgledbloc,lsaa012,other,lgesp,lessthan3months,1,1,0.003079,0.193276,corporate/office,engineering,167

In [35]:
train_x.head()

,bant_submit,customer_country,business_unit,com_reg_ver_win_rate,customer_idx,customer_type,enterprise,historical_existing_cnt,id_strategic_ver,it_strategic_ver,idit_strategic_ver,customer_job,lead_desc_length,inquiry_type,product_category,product_subcategory,product_modelname,customer_position,response_corporate,expected_timeline,ver_cus,ver_pro,ver_win_rate_x,ver_win_ratio_per_bu,business_area,business_subarea,lead_owner
0,1.0,philippines,as,0.063118,32160,end-customer,enterprise,0.000000,0,0,0,educator,0.048298,quotationorpurchaseconsultation,multi-split,0,0,entrylevel,lgeph,lessthan3months,1,0,0.003079,0.055676,corporate/office,engineering,0
1,1.0,philippines,as,0.063118,23122,end-customer,enterprise,0.008608,0,0,0,educator,0.075218,quotationorpurchaseconsultation,multi-split,0,0,ceo/founder,lgeph,lessthan3months,1,0,0.003079,0.055676,corporate/office,advertising,1
2,1.0,india,as,0.085425,1755,end-customer,enterprise,0.103300,0,0,0,engineer,0.043547,productinformation,single-split,0,0,partner,lgeil,lessthan3months,1,0,0.003079,0.055676,corporate/office,construction,2
3,1.0,india,as,0.085425,4919,end-customer,enterprise,0.000000,0,0,0,educator,0.034046,quotationorpurchaseconsultation,vrf,0,0,ceo/founder,lgeil,lessthan3months,1,0,0.003079,0.055676,corporate/office,it/software,3
4,1.0,india,as,0.085425,17126,specifier/influencer,enterprise,0.000000,0,0,0,consultant,0.076010,quotationorpurchaseconsultation,multi-split,0,0,partner,lgeil,lessthan3months,0,0,0.003079,0.055676,corporate/office,0,4

In [36]:
x_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5271 entries, 0 to 5270
Data columns (total 27 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   bant_submit              5271 non-null   float64
 1   customer_country         5239 non-null   object
 2   business_unit            5271 non-null   object
 3   com_reg_ver_win_rate     1788 non-null   float64
 4   customer_idx             5271 non-null   object
 5   customer_type            3814 non-null   object
 6   enterprise               5271 non-null   object
 7   historical_existing_cnt  1275 non-null   float64
 8   id_strategic_ver         5271 non-null   object
 9   it_strategic_ver         5271 non-null   object
 10  idit_strategic_ver       5271 non-null   object
 11  customer_job             3832 non-null   object
 12  lead_desc_length         5271 non-null   float64
 13  inquiry_type             3979 non-null   object
 14  product_category         3413 non-null   object
 15  product_subcategory      793 non-null    object
 16  product_modelname        562 non-null    object
 17  customer_position        5271 non-null   object
 18  response_corporate       5271 non-null   object
 19  expected_timeline        2863 non-null   object
 20  ver_cus                  5271 non-null   object
 21  ver_pro                  5271 non-null   object
 22  ver_win_rate_x           2373 non-null   float64
 23  ver_win_ratio_per_bu     1906 non-null   float64
 24  business_area            2373 non-null   object
 25  business_subarea         1816 non-null   object
 26  lead_owner               5271 non-null   object
dtypes: float64(6), object(21)
memory usage: 1.1+ MB

In [37]:
test_pred = best_classification_model.predict(x_test.fillna(0))
print(test_pred)
sum(int(pred == 1) for pred in test_pred)

[1 1 1 ... 0 0 1]

1493

### 제출 파일 작성

In [38]:
# 제출 데이터 읽어오기 (df_test는 전처리된 데이터가 저장됨)
df_sub = pd.read_csv("submission.csv")
df_sub["is_converted"] = test_pred

# 제출 파일 저장
df_sub.to_csv("submission.csv", index=False)

In [39]:
best_classification_model.get_feature_importance(prettified=True)

                 Feature Id  Importances
0              customer_idx    16.310723
1                lead_owner    14.426441
2             customer_type    13.169318
3          product_category     7.076863
4        response_corporate     7.072574
5              inquiry_type     4.655349
6          lead_desc_length     4.066806
7             business_area     3.591807
8              customer_job     3.579795
9             business_unit     3.280487
10         customer_country     2.770911
11               enterprise     2.518242
12  historical_existing_cnt     2.405464
13        customer_position     2.091022
14        expected_timeline     2.079404
15     com_reg_ver_win_rate     1.992112
16           ver_win_rate_x     1.972221
17         business_subarea     1.884698
18        product_modelname     1.709537
19      product_subcategory     1.183842
20              bant_submit     1.014082
21     ver_win_ratio_per_bu     0.451196
22         id_strategic_ver     0.447769
23       idit_strategic_ver     0.121767
24                  ver_cus     0.102549
25                  ver_pro     0.025021
26         it_strategic_ver     0.000000

**우측 상단의 제출 버튼을 클릭해 결과를 확인하세요**