# 영업 성공 여부 분류 경진대회

## 1. 데이터 확인

### 필수 라이브러리

In [ ]:
import pandas as pd
import numpy as np
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
)
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

def seed_everything(seed):
    np.random.seed(seed) #numpy를 사용할 경우 고정
seed_everything(42)

### 데이터 셋 읽어오기

In [ ]:
df_train = pd.read_csv("train.csv") # 학습용 데이터
df_test = pd.read_csv("submission.csv") # 테스트 데이터(제출파일의 데이터)

### 삭제할 컬럼

In [ ]:
drop_columns = [
    'customer_type',
    'ver_win_ratio_per_bu',
    'com_reg_ver_win_rate',
    'historical_existing_cnt',
    'product_subcategory',
    'product_modelname',
    'business_subarea',
    'idit_strategic_ver',
    'id_strategic_ver',
    'it_strategic_ver'
]

pre_train = df_train.drop(labels = drop_columns,axis=1)
pre_test = df_test.drop(labels = drop_columns + ['id'],axis=1)

In [19]:
print(len(df_train.columns))
print(len(pre_train.columns))

29
19

In [20]:
# 1. 분석의 목적과 목적에 맞는 변수 확인
# 데이터의 구조와 변수 목록을 살펴봅니다.
print("데이터 정보:")
print(df_train.info())

# 2. 데이터형 확인 및 데이터 오류/누락 여부 확인
# 각 열의 데이터 유형 및 결측치 확인
print("\n\n\n데이터 유형 및 결측치:")
print(df_train.dtypes)
print(df_train.isnull().sum())

# 3. 데이터 분포 확인
# 데이터의 기술 통계량을 계산하여 분포를 확인합니다.
print("\n\n\n데이터 기술 통계량:")
print(df_train.describe())

데이터 정보:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59299 entries, 0 to 59298
Data columns (total 29 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   bant_submit              59299 non-null  float64
 1   customer_country         58317 non-null  object
 2   business_unit            59299 non-null  object
 3   com_reg_ver_win_rate     14568 non-null  float64
 4   customer_idx             59299 non-null  int64
 5   customer_type            15338 non-null  object
 6   enterprise               59299 non-null  object
 7   historical_existing_cnt  13756 non-null  float64
 8   id_strategic_ver         3444 non-null   float64
 9   it_strategic_ver         1121 non-null   float64
 10  idit_strategic_ver       4565 non-null   float64
 11  customer_job             40566 non-null  object
 12  lead_desc_length         59299 non-null  int64
 13  inquiry_type             58358 non-null  object
 14  product_category         39925 non-null  object
 15  product_subcategory      9235 non-null   object
 16  product_modelname        9229 non-null   object
 17  customer_country.1       58317 non-null  object
 18  customer_position        59299 non-null  object
 19  response_corporate       59299 non-null  object
 20  expected_timeline        28436 non-null  object
 21  ver_cus                  59299 non-null  int64
 22  ver_pro                  59299 non-null  int64
 23  ver_win_rate_x           18417 non-null  float64
 24  ver_win_ratio_per_bu     15304 non-null  float64
 25  business_area            18417 non-null  object
 26  business_subarea         5526 non-null   object
 27  lead_owner               59299 non-null  int64
 28  is_converted             59299 non-null  bool
dtypes: bool(1), float64(8), int64(5), object(15)
memory usage: 12.7+ MB
None



데이터 유형 및 결측치:
bant_submit                float64
customer_country            object
business_unit               object
com_reg_ver_win_rate       float64
customer_idx                 int64
customer_type               object
enterprise                  object
historical_existing_cnt    float64
id_strategic_ver           float64
it_strategic_ver           float64
idit_strategic_ver         float64
customer_job                object
lead_desc_length             int64
inquiry_type                object
product_category            object
product_subcategory         object
product_modelname           object
customer_country.1          object
customer_position           object
response_corporate          object
expected_timeline           object
ver_cus                      int64
ver_pro                      int64
ver_win_rate_x             float64
ver_win_ratio_per_bu       float64
business_area               object
business_subarea            object
lead_owner                   int64
is_converted                  bool
dtype: object
bant_submit                    0
customer_country             982
business_unit                  0
com_reg_ver_win_rate       44731
customer_idx                   0
customer_type              43961
enterprise                     0
historical_existing_cnt    45543
id_strategic_ver           55855
it_strategic_ver           58178
idit_strategic_ver         54734
customer_job               18733
lead_desc_length               0
inquiry_type                 941
product_category           19374
product_subcategory        50064
product_modelname          50070
customer_country.1           982
customer_position              0
response_corporate             0
expected_timeline          30863
ver_cus                        0
ver_pro                        0
ver_win_rate_x             40882
ver_win_ratio_per_bu       43995
business_area              40882
business_subarea           53773
lead_owner                     0
is_converted                   0
dtype: int64



데이터 기술 통계량:
        bant_submit  com_reg_ver_win_rate  customer_idx  \
count  59299.000000          14568.000000  59299.000000
mean       0.634593              0.091685  27114.556333
std        0.286066              0.150988  14653.911888
min        0.000000              0.003788      2.000000
25%        0.500000              0.019900  14913.000000
50%        0.500000              0.049180  26774.000000
75%        1.000000              0.074949  40368.500000
max        1.000000              1.000000  47466.000000

       historical_existing_cnt  id_strategic_ver  it_strategic_ver  \
count             13756.000000            3444.0            1121.0
mean                 19.912184               1.0               1.0
std                  44.697938               0.0               0.0
min                   0.000000               1.0               1.0
25%                   1.000000               1.0               1.0
50%                   4.000000               1.0               1.0
75%                  19.000000               1.0               1.0
max                1394.000000               1.0               1.0

       idit_strategic_ver  lead_desc_length       ver_cus       ver_pro  \
count              4565.0      59299.000000  59299.000000  59299.000000
mean                  1.0         79.271590      0.041603      0.050810
std                   0.0        132.551067      0.199681      0.219612
min                   1.0          1.000000      0.000000      0.000000
25%                   1.0          7.000000      0.000000      0.000000
50%                   1.0         29.000000      0.000000      0.000000
75%                   1.0         92.000000      0.000000      0.000000
max                   1.0       1264.000000      1.000000      1.000000

       ver_win_rate_x  ver_win_ratio_per_bu    lead_owner
count    18417.000000          15304.000000  59299.000000
mean         0.001117              0.049288    262.563888
std          0.001104              0.027949    231.605681
min          0.000002              0.011583      0.000000
25%          0.000298              0.026846     97.000000
50%          0.000572              0.049840    175.000000
75%          0.001183              0.064566    374.000000
max          0.003079              0.285714   1114.000000

In [21]:
# 결측치가 있는 변수 및 결측률 파악 - 결측률이 0.7이상인 column 17개 제거 ?

mis_val = df_train.isnull().sum()
mis_val_bool = mis_val >= 1
mis_val_df = pd.concat([mis_val, mis_val_bool], axis = 1)
mis_val_df = mis_val_df.rename(columns = {0 : 'mis_val', 1 : 'mis_val_bool'})

mis_val_data = mis_val_df.loc[mis_val_df['mis_val_bool'] == True, :]
mis_val_data['ratio'] = mis_val_data['mis_val'] / 59299
mis_val_data_sorted = mis_val_data.sort_values(by='ratio', ascending=True)
mis_val_data_sorted

/tmp/ipykernel_356/1160255513.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mis_val_data['ratio'] = mis_val_data['mis_val'] / 59299

                         mis_val  mis_val_bool     ratio
inquiry_type                 941          True  0.015869
customer_country.1           982          True  0.016560
customer_country             982          True  0.016560
customer_job               18733          True  0.315908
product_category           19374          True  0.326717
expected_timeline          30863          True  0.520464
business_area              40882          True  0.689421
ver_win_rate_x             40882          True  0.689421
customer_type              43961          True  0.741345
ver_win_ratio_per_bu       43995          True  0.741918
com_reg_ver_win_rate       44731          True  0.754330
historical_existing_cnt    45543          True  0.768023
product_subcategory        50064          True  0.844264
product_modelname          50070          True  0.844365
business_subarea           53773          True  0.906811
idit_strategic_ver         54734          True  0.923017
id_strategic_ver           55855          True  0.941921
it_strategic_ver           58178          True  0.981096

In [22]:
df_train[['customer_country','customer_country.1']].head()

           customer_country        customer_country.1
0  /Quezon City/Philippines  /Quezon City/Philippines
1        /PH-00/Philippines        /PH-00/Philippines
2           /Kolkata /India           /Kolkata /India
3        /Bhubaneswar/India        /Bhubaneswar/India
4          /Hyderabad/India          /Hyderabad/India

In [23]:
# customer_country와 customer_country.1이 동시에 결측값을 가지는 행의 개수 
df_train[df_train['customer_country.1'].isnull() & df_train['customer_country'].isnull()].shape[0]

982

In [24]:
pre_train = pre_train.dropna(subset=['customer_country'])

In [25]:
mis_val = pre_train.isnull().sum()
mis_val_bool = mis_val >= 1
mis_val_df = pd.concat([mis_val, mis_val_bool], axis = 1)
mis_val_df = mis_val_df.rename(columns = {0 : 'mis_val', 1 : 'mis_val_bool'})

mis_val_data = mis_val_df.loc[mis_val_df['mis_val_bool'] == True, :]
mis_val_data['ratio'] = mis_val_data['mis_val'] / 59299
mis_val_data_sorted = mis_val_data.sort_values(by='ratio', ascending=True)
mis_val_data_sorted

/tmp/ipykernel_356/2599025825.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mis_val_data['ratio'] = mis_val_data['mis_val'] / 59299

                   mis_val  mis_val_bool     ratio
inquiry_type           369          True  0.006223
customer_job         18184          True  0.306649
product_category     18920          True  0.319061
expected_timeline    29991          True  0.505759
ver_win_rate_x       40704          True  0.686420
business_area        40704          True  0.686420

In [26]:
pre_train['customer_country'] = pre_train['customer_country'].apply(lambda x: x.split('/')[-1])
df_test['customer_country'] = df_test['customer_country'].apply(lambda x: x.split('/')[-1])

In [27]:
pre_train.head()

,bant_submit,customer_country,business_unit,customer_idx,enterprise,customer_job,lead_desc_length,inquiry_type,product_category,customer_country.1,customer_position,response_corporate,expected_timeline,ver_cus,ver_pro,ver_win_rate_x,business_area,lead_owner,is_converted
0,1.0,Philippines,AS,32160,Enterprise,purchasing,62,Quotation or purchase consultation,multi-split,/Quezon City/Philippines,entry level,LGEPH,less than 3 months,1,0,0.003079,corporate / office,0,True
1,1.0,Philippines,AS,23122,Enterprise,media and communication,96,Quotation or purchase consultation,multi-split,/PH-00/Philippines,ceo/founder,LGEPH,less than 3 months,1,0,0.003079,corporate / office,1,True
2,1.0,India,AS,1755,Enterprise,engineering,56,Product Information,single-split,/Kolkata /India,partner,LGEIL,less than 3 months,1,0,0.003079,corporate / office,2,True
3,1.0,India,AS,4919,Enterprise,entrepreneurship,44,Quotation or purchase consultation,vrf,/Bhubaneswar/India,ceo/founder,LGEIL,less than 3 months,1,0,0.003079,corporate / office,3,True
4,1.0,India,AS,17126,Enterprise,consulting,97,Quotation or purchase consultation,multi-split,/Hyderabad/India,partner,LGEIL,less than 3 months,0,0,0.003079,corporate / office,4,True

## 2. 데이터 전처리

### 레이블 인코딩

In [28]:
def label_encoding(series: pd.Series) -> pd.Series:
    """범주형 데이터를 시리즈 형태로 받아 숫자형 데이터로 변환합니다."""

    my_dict = {}

    # 모든 요소를 문자열로 변환
    series = series.astype(str)

    for idx, value in enumerate(sorted(series.unique())):
        my_dict[value] = idx
    series = series.map(my_dict)

    return series

In [29]:
# 레이블 인코딩할 칼럼들
label_columns = [
    "customer_country",
    "business_subarea",
    "business_area",
    "business_unit",
    "customer_type",
    "enterprise",
    "customer_job",
    "inquiry_type",
    "product_category",
    "product_subcategory",
    "product_modelname",
    "customer_country.1",
    "customer_position",
    "response_corporate",
    "expected_timeline",
]

label_columns = list(set(label_columns)-set(drop_columns))

df_all = pd.concat([pre_train[label_columns], pre_test[label_columns]])

for col in label_columns:
    df_all[col] = label_encoding(df_all[col])

In [30]:
df_all.head()

,customer_job,product_category,enterprise,response_corporate,expected_timeline,business_unit,business_area,customer_country,inquiry_type,customer_position,customer_country.1
0,416,148,0,33,245,0,0,2812,25,44,9070
1,299,148,0,33,245,0,0,2812,25,18,8406
2,156,201,0,21,245,0,0,2713,20,75,6535
3,162,272,0,21,245,0,0,2713,25,18,3388
4,82,148,0,21,245,0,0,2713,25,75,5799

다시 학습 데이터와 제출 데이터를 분리합니다.

In [31]:
for col in label_columns:  
    pre_train[col] = df_all.iloc[: len(pre_train)][col]
    pre_test[col] = df_all.iloc[len(pre_train) :][col]

In [32]:
t = pre_train.copy()
corr = t.corr()
corr.style.background_gradient(cmap = 'coolwarm')

In [33]:
pre_train = pre_train.drop(labels = ['customer_country.1'],axis=1)
pre_test = pre_test.drop(labels = ['customer_country.1'],axis=1)

In [34]:
print(pre_train.columns)
print("\n\n\n")
print(pre_test.columns)

Index(['bant_submit', 'customer_country', 'business_unit', 'customer_idx',
       'enterprise', 'customer_job', 'lead_desc_length', 'inquiry_type',
       'product_category', 'customer_position', 'response_corporate',
       'expected_timeline', 'ver_cus', 'ver_pro', 'ver_win_rate_x',
       'business_area', 'lead_owner', 'is_converted'],
      dtype='object')




Index(['bant_submit', 'customer_country', 'business_unit', 'customer_idx',
       'enterprise', 'customer_job', 'lead_desc_length', 'inquiry_type',
       'product_category', 'customer_position', 'response_corporate',
       'expected_timeline', 'ver_cus', 'ver_pro', 'ver_win_rate_x',
       'business_area', 'lead_owner', 'is_converted'],
      dtype='object')

### 2-2. 학습, 검증 데이터 분리

In [35]:
x_train, x_val, y_train, y_val = train_test_split(
    pre_train.drop("is_converted", axis=1),
    pre_train["is_converted"],
    test_size=0.2,
    shuffle=True,
    random_state=400,
)

## 3. 모델 학습

### 모델 정의

In [37]:
model = DecisionTreeClassifier(random_state=42)

### 모델 학습

In [38]:
model.fit(x_train.fillna(0), y_train)

DecisionTreeClassifier(random_state=42)

### 모델 성능 보기

In [39]:
def get_clf_eval(y_test, y_pred=None):
    confusion = confusion_matrix(y_test, y_pred, labels=[True, False])
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, labels=[True, False])
    recall = recall_score(y_test, y_pred)
    F1 = f1_score(y_test, y_pred, labels=[True, False])

    print("오차행렬:\n", confusion)
    print("\n정확도: {:.4f}".format(accuracy))
    print("정밀도: {:.4f}".format(precision))
    print("재현율: {:.4f}".format(recall))
    print("F1: {:.4f}".format(F1))

In [40]:
pred = model.predict(x_val.fillna(0))
get_clf_eval(y_val, pred)

오차행렬:
 [[  745   211]
 [  235 10473]]

정확도: 0.9618
정밀도: 0.7602
재현율: 0.7793
F1: 0.7696

## 4. 제출하기

### 테스트 데이터 예측

In [41]:
# 예측에 필요한 데이터 분리
x_test = pre_test.drop(["is_converted"], axis=1)

In [42]:
test_pred = model.predict(x_test.fillna(0))
sum(test_pred) # True로 예측된 개수

1050

### 제출 파일 작성

In [ ]:
# 제출 데이터 읽어오기 (df_test는 전처리된 데이터가 저장됨)
df_sub = pd.read_csv("submission.csv")
df_sub["is_converted"] = test_pred

# 제출 파일 저장
df_sub.to_csv("submission.csv", index=False)

**우측 상단의 제출 버튼을 클릭해 결과를 확인하세요**